services:
  react:
    image: 'nginx:latest'
    container_name: react
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./myproj/build:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server

  server:
    build: ./myproj_server
    container_name: server
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - ./myproj_server/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
