services:
  react:
    build:
      context: .
      dockerfile: ./myproj/Dockerfile
    container_name: react
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./myproj/build:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - certbot
    networks:
      - app_network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
    networks:
      - app_network

  server:
    build: ./myproj_server
    container_name: server
    restart: always
    expose:
      - "5000"
    env_file:
      - ./myproj_server/.env
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
